# Generated by Django 6.0 on 2025-12-20 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atestado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(verbose_name='Data/Hora Início')),
                ('data_fim', models.DateTimeField(verbose_name='Data/Hora Fim')),
                ('protocolo_prefeitura', models.CharField(blank=True, max_length=50, verbose_name='Protocolo da Prefeitura')),
                ('arquivo', models.FileField(upload_to='atestados/', verbose_name='Arquivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atestados_criados', to=settings.AUTH_USER_MODEL)),
                ('usuario_alvo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atestados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atestado',
                'verbose_name_plural': 'Atestados',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('cin', models.CharField(max_length=20, verbose_name='CIN')),
                ('nome_social', models.CharField(blank=True, max_length=255, verbose_name='Nome Social')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('data_entrada', models.DateField(verbose_name='Data de Entrada')),
                ('bolsa_familia', models.BooleanField(default=False, verbose_name='Bolsa Família')),
                ('pe_de_meia', models.BooleanField(default=True, verbose_name='Pé de Meia')),
                ('usa_onibus', models.BooleanField(default=True, verbose_name='Usa Ônibus Escolar')),
                ('linha_onibus', models.CharField(blank=True, max_length=100, verbose_name='Linha do Ônibus')),
                ('permissao_sair_sozinho', models.BooleanField(default=False, verbose_name='Permissão para Sair Sozinho')),
                ('logradouro', models.CharField(max_length=255, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(default='Mogi Guaçu', max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(default='SP', max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estudante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estudante',
                'verbose_name_plural': 'Estudantes',
                'ordering': ['usuario__first_name', 'usuario__last_name'],
            },
        ),
        migrations.CreateModel(
            name='MatriculaCEMEP',
            fields=[
                ('numero_matricula', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Número da Matrícula')),
                ('data_entrada', models.DateField(verbose_name='Data de Entrada')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data de Saída')),
                ('status', models.CharField(choices=[('MATRICULADO', 'Matriculado'), ('CONCLUIDO', 'Concluído'), ('ABANDONO', 'Abandono'), ('TRANSFERIDO', 'Transferido'), ('OUTRO', 'Outro')], default='MATRICULADO', max_length=20, verbose_name='Status')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='core.curso')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_cemep', to='academic.estudante')),
            ],
            options={
                'verbose_name': 'Matrícula CEMEP',
                'verbose_name_plural': 'Matrículas CEMEP',
                'ordering': ['-data_entrada'],
            },
        ),
        migrations.CreateModel(
            name='MatriculaTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField(verbose_name='Data de Entrada')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data de Saída')),
                ('status', models.CharField(choices=[('CURSANDO', 'Cursando'), ('TRANSFERIDO', 'Transferido'), ('RETIDO', 'Retido'), ('PROMOVIDO', 'Promovido')], default='CURSANDO', max_length=20, verbose_name='Status')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_turma', to='academic.estudante')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='core.turma')),
            ],
            options={
                'verbose_name': 'Matrícula na Turma',
                'verbose_name_plural': 'Matrículas nas Turmas',
                'ordering': ['-turma__ano_letivo', 'estudante__usuario__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
            },
        ),
        migrations.CreateModel(
            name='ResponsavelEstudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(choices=[('PAI', 'Pai'), ('MAE', 'Mãe'), ('AVO_M', 'Avô(a) Materno'), ('AVO_P', 'Avô(a) Paterno'), ('TIO', 'Tio(a)'), ('IRMAO', 'Irmão(ã)'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Parentesco')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.estudante')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.responsavel')),
            ],
            options={
                'verbose_name': 'Vínculo Responsável-Estudante',
                'verbose_name_plural': 'Vínculos Responsáveis-Estudantes',
                'unique_together': {('responsavel', 'estudante')},
            },
        ),
        migrations.AddField(
            model_name='responsavel',
            name='estudantes',
            field=models.ManyToManyField(related_name='responsaveis', through='academic.ResponsavelEstudante', to='academic.estudante'),
        ),
    ]
