# Generated by Django 6.0 on 2026-01-14 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atestado',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atestados_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atestado',
            name='usuario_alvo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atestados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estudante',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estudante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matriculacemep',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='core.curso'),
        ),
        migrations.AddField(
            model_name='matriculacemep',
            name='estudante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_cemep', to='academic.estudante'),
        ),
        migrations.AddField(
            model_name='matriculaturma',
            name='matricula_cemep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_turma', to='academic.matriculacemep', verbose_name='Matrícula CEMEP'),
        ),
        migrations.AddField(
            model_name='matriculaturma',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='core.turma'),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='responsavelestudante',
            name='estudante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.estudante'),
        ),
        migrations.AddField(
            model_name='responsavelestudante',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.responsavel'),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='estudantes',
            field=models.ManyToManyField(related_name='responsaveis', through='academic.ResponsavelEstudante', to='academic.estudante'),
        ),
        migrations.AlterUniqueTogether(
            name='matriculacemep',
            unique_together={('estudante', 'curso')},
        ),
        migrations.AlterUniqueTogether(
            name='matriculaturma',
            unique_together={('matricula_cemep', 'turma')},
        ),
        migrations.AlterUniqueTogether(
            name='responsavelestudante',
            unique_together={('responsavel', 'estudante')},
        ),
    ]
