# Generated by Django 6.0 on 2025-12-30 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
        ('core', '0005_horarioaula_gradehoraria'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matriculacemep',
            unique_together={('estudante', 'curso')},
        ),
        migrations.AlterUniqueTogether(
            name='matriculaturma',
            unique_together={('matricula_cemep', 'turma')},
        ),
    ]
