# Generated by Django 6.0 on 2026-01-01 20:20

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='cpf',
            field=models.CharField(blank=True, help_text='Opcional para dados legados. Único quando preenchido.', max_length=14, null=True, unique=True, validators=[apps.core.validators.validate_cpf], verbose_name='CPF'),
        ),
    ]
