# Generated by Django 6.0 on 2025-12-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='cin',
            field=models.CharField(blank=True, max_length=20, verbose_name='CIN'),
        ),
    ]
