# Generated by Django 6.0 on 2026-01-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_alter_estudante_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculaturma',
            name='status',
            field=models.CharField(choices=[('CURSANDO', 'Cursando'), ('TRANSFERIDO', 'Transferido'), ('RETIDO', 'Retido'), ('PROMOVIDO', 'Promovido'), ('ABANDONO', 'Abandono'), ('OUTRO', 'Outro')], default='CURSANDO', max_length=20, verbose_name='Status'),
        ),
    ]
