GESTAO        = "GESTAO"
SECRETARIA    = "SECRETARIA"
PROFESSOR     = "PROFESSOR"
MONITOR       = "MONITOR"
ESTUDANTE     = "ESTUDANTE"
RESPONSAVEL   = "RESPONSAVEL"

AUTHENTICATED = "AUTHENTICATED"
OWNER         = "OWNER"

# Constantes complementares
NONE        = "NONE"        # Bloqueia operação explicitamente
FUNCIONARIO = "FUNCIONARIO" # Grupo: GESTAO, SECRETARIA, PROFESSOR, MONITOR

# Expansão do grupo FUNCIONARIO
FUNCIONARIO_TIPOS = {GESTAO, SECRETARIA, PROFESSOR, MONITOR}

# Combinações Comuns (Grupos)
ADMIN   = [GESTAO, SECRETARIA]
DOCENTE = [PROFESSOR, MONITOR]
ALUNO   = [ESTUDANTE, RESPONSAVEL]
