GESTAO        = "GESTAO"
SECRETARIA    = "SECRETARIA"
PROFESSOR     = "PROFESSOR"
MONITOR       = "MONITOR"
ESTUDANTE     = "ESTUDANTE"
RESPONSAVEL   = "RESPONSAVEL"

AUTHENTICATED = "AUTHENTICATED"
OWNER         = "OWNER"
