# Generated by Django 6.0 on 2025-12-21 16:41

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Número')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('ano_letivo', models.PositiveSmallIntegerField(verbose_name='Ano Letivo')),
            ],
            options={
                'verbose_name': 'Bimestre',
                'verbose_name_plural': 'Bimestres',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='CalendarioEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True, verbose_name='Data')),
                ('ano_letivo', models.PositiveSmallIntegerField(db_index=True, verbose_name='Ano Letivo')),
                ('letivo', models.BooleanField(default=True, verbose_name='Dia Letivo')),
                ('tipo', models.CharField(blank=True, choices=[('FERIADO', 'Feriado'), ('PONTO_FACULTATIVO', 'Ponto Facultativo'), ('RECESSO', 'Recesso'), ('FERIAS', 'Férias')], max_length=20, null=True, verbose_name='Tipo (se não letivo)')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Calendário Escolar',
                'verbose_name_plural': 'Calendário Escolar',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=10, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=10, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.PositiveIntegerField(help_text='Número de matrícula do funcionário', verbose_name='Nº Matrícula')),
                ('area_atuacao', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Área de Atuação')),
                ('apelido', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Apelido')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['usuario__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descricao', ckeditor.fields.RichTextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['disciplina', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField(verbose_name='Data de Entrada')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data de Saída')),
            ],
            options={
                'verbose_name': 'Período de Trabalho',
                'verbose_name_plural': 'Períodos de Trabalho',
                'ordering': ['-data_entrada'],
            },
        ),
        migrations.CreateModel(
            name='ProfessorDisciplinaTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Atribuição de Aulas',
                'verbose_name_plural': 'Atribuições de Aulas',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Número')),
                ('letra', models.CharField(max_length=1, verbose_name='Letra')),
                ('ano_letivo', models.PositiveSmallIntegerField(verbose_name='Ano Letivo')),
                ('nomenclatura', models.CharField(choices=[('SERIE', 'Série'), ('ANO', 'Ano'), ('MODULO', 'Módulo')], default='ANO', max_length=10, verbose_name='Nomenclatura')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['-ano_letivo', 'numero', 'letra'],
            },
        ),
        migrations.CreateModel(
            name='DisciplinaTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aulas_semanais', models.PositiveSmallIntegerField(verbose_name='Aulas Semanais')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas_vinculadas', to='core.disciplina')),
            ],
            options={
                'verbose_name': 'Disciplina da Turma',
                'verbose_name_plural': 'Disciplinas das Turmas',
            },
        ),
    ]
