# Generated by Django 6.0 on 2025-12-31 00:19

import apps.core.validators
import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=10, unique=True, verbose_name='Sigla')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DiaLetivoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True, verbose_name='Data do Dia Letivo')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Motivo/Descrição')),
            ],
            options={
                'verbose_name': 'Dia Letivo Extra',
                'verbose_name_plural': 'Dias Letivos Extras',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='DiaNaoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True, verbose_name='Data da Ocorrência')),
                ('tipo', models.CharField(choices=[('FERIADO', 'Feriado'), ('PONTO_FACULTATIVO', 'Ponto facultativo'), ('RECESSO', 'Recesso escolar'), ('FERIAS', 'Férias escolares'), ('SUSPENSO', 'Dia letivo suspenso'), ('PLANEJAMENTO', 'Planejamento'), ('OUTROS', 'Outros')], max_length=30, verbose_name='Categoria do Dia')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Motivo/Descrição')),
            ],
            options={
                'verbose_name': 'Dia Não Letivo',
                'verbose_name_plural': 'Dias Não Letivos',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.PositiveIntegerField(help_text='Número de matrícula do funcionário', verbose_name='Nº Matrícula')),
                ('area_atuacao', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Área de Atuação')),
                ('apelido', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Apelido')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[apps.core.validators.validate_cpf], verbose_name='CPF')),
                ('cin', models.CharField(blank=True, max_length=20, verbose_name='CIN')),
                ('nome_social', models.CharField(blank=True, max_length=255, verbose_name='Nome Social')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('logradouro', models.CharField(default='', max_length=255, verbose_name='Logradouro')),
                ('numero', models.CharField(default='', max_length=10, verbose_name='Número')),
                ('bairro', models.CharField(default='', max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(default='Paulínia', max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(default='SP', max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(default='', max_length=8, verbose_name='CEP')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('telefone', models.CharField(blank=True, max_length=15, verbose_name='Telefone')),
                ('data_admissao', models.DateField(blank=True, null=True, verbose_name='Data de Admissão')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['usuario__first_name'],
            },
        ),
        migrations.CreateModel(
            name='GradeHoraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Grade Horária',
                'verbose_name_plural': 'Grades Horárias',
                'ordering': ['horario_aula__dia_semana', 'horario_aula__hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descricao', ckeditor.fields.RichTextField(verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['disciplina', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='HorarioAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Número da aula')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de início')),
                ('hora_fim', models.TimeField(verbose_name='Hora de fim')),
            ],
            options={
                'verbose_name': 'Horário de Aula',
                'verbose_name_plural': 'Horários de Aula',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField(verbose_name='Data de Entrada')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data de Saída')),
            ],
            options={
                'verbose_name': 'Período de Trabalho',
                'verbose_name_plural': 'Períodos de Trabalho',
                'ordering': ['-data_entrada'],
            },
        ),
        migrations.CreateModel(
            name='ProfessorDisciplinaTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TITULAR', 'Titular'), ('SUBSTITUTO', 'Substituto'), ('AUXILIAR', 'Auxiliar')], default='TITULAR', max_length=15, verbose_name='Tipo')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
            ],
            options={
                'verbose_name': 'Atribuição de Professor',
                'verbose_name_plural': 'Atribuições de Professores',
                'ordering': ['tipo', 'professor__usuario__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Número')),
                ('letra', models.CharField(max_length=1, verbose_name='Letra')),
                ('ano_letivo', models.PositiveSmallIntegerField(verbose_name='Ano Letivo')),
                ('nomenclatura', models.CharField(choices=[('SERIE', 'Série'), ('ANO', 'Ano'), ('MODULO', 'Módulo')], default='ANO', max_length=10, verbose_name='Nomenclatura')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['-ano_letivo', 'numero', 'letra'],
            },
        ),
        migrations.CreateModel(
            name='AnoLetivo',
            fields=[
                ('ano', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Ano')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('data_inicio_1bim', models.DateField(blank=True, null=True, verbose_name='Data de Início do 1º Bimestre')),
                ('data_fim_1bim', models.DateField(blank=True, null=True, verbose_name='Data de Fim do 1º Bimestre')),
                ('data_inicio_2bim', models.DateField(blank=True, null=True, verbose_name='Data de Início do 2º Bimestre')),
                ('data_fim_2bim', models.DateField(blank=True, null=True, verbose_name='Data de Fim do 2º Bimestre')),
                ('data_inicio_3bim', models.DateField(blank=True, null=True, verbose_name='Data de Início do 3º Bimestre')),
                ('data_fim_3bim', models.DateField(blank=True, null=True, verbose_name='Data de Fim do 3º Bimestre')),
                ('data_inicio_4bim', models.DateField(blank=True, null=True, verbose_name='Início do 4º Bimestre')),
                ('data_fim_4bim', models.DateField(blank=True, null=True, verbose_name='Fim do 4º Bimestre')),
                ('dias_letivos_extras', models.ManyToManyField(blank=True, to='core.dialetivoextra', verbose_name='Dias Letivos Especiais')),
                ('dias_nao_letivos', models.ManyToManyField(blank=True, to='core.dianaoletivo', verbose_name='Feriados e Recessos')),
            ],
            options={
                'verbose_name': 'Ano Letivo',
                'verbose_name_plural': 'Anos Letivos',
                'ordering': ['-ano'],
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=10, verbose_name='Sigla')),
                ('area_conhecimento', models.CharField(blank=True, choices=[('LINGUAGENS', 'Linguagens e suas Tecnologias'), ('MATEMATICA', 'Matemática e suas Tecnologias'), ('CIENCIAS_NATUREZA', 'Ciências da Natureza e suas Tecnologias'), ('CIENCIAS_HUMANAS', 'Ciências Humanas e Sociais Aplicadas'), ('TEC_INFORMATICA', 'Técnico em Informática'), ('TEC_QUIMICA', 'Técnico em Química'), ('TEC_ENFERMAGEM', 'Técnico em Enfermagem')], max_length=20, null=True, verbose_name='Área de Conhecimento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['nome'],
                'unique_together': {('nome', 'sigla')},
            },
        ),
        migrations.CreateModel(
            name='DisciplinaTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aulas_semanais', models.PositiveSmallIntegerField(default=4, verbose_name='Aulas Semanais')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas_vinculadas', to='core.disciplina')),
            ],
            options={
                'verbose_name': 'Disciplina da Turma',
                'verbose_name_plural': 'Disciplinas das Turmas',
            },
        ),
    ]
