# Generated by Django 6.0 on 2026-01-15 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anoletivoselecionado',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano_letivo_selecionado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquivos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controleregistrosvisualizacao',
            name='ano_letivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controle_registros_visualizacao', to='core.anoletivo', verbose_name='Ano Letivo'),
        ),
        migrations.AddField(
            model_name='anoletivo',
            name='dias_letivos_extras',
            field=models.ManyToManyField(blank=True, to='core.dialetivoextra', verbose_name='Dias Letivos Especiais'),
        ),
        migrations.AddField(
            model_name='anoletivo',
            name='dias_nao_letivos',
            field=models.ManyToManyField(blank=True, to='core.dianaoletivo', verbose_name='Feriados e Recessos'),
        ),
        migrations.AddField(
            model_name='disciplinaturma',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas_vinculadas', to='core.disciplina'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradehoraria',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades_horarias', to='core.curso', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='gradehoraria',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades_horarias', to='core.disciplina', verbose_name='Disciplina'),
        ),
        migrations.AddField(
            model_name='gradehorariavalidade',
            name='ano_letivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validades_grade', to='core.anoletivo', verbose_name='Ano Letivo'),
        ),
        migrations.AddField(
            model_name='gradehoraria',
            name='validade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_grade', to='core.gradehorariavalidade', verbose_name='Vigência'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='habilidades',
            field=models.ManyToManyField(blank=True, related_name='disciplinas', to='core.habilidade', verbose_name='Habilidades BNCC'),
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='ano_letivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_aula', to='core.anoletivo', verbose_name='Ano Letivo'),
        ),
        migrations.AddField(
            model_name='gradehoraria',
            name='horario_aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades_horarias', to='core.horarioaula', verbose_name='Horário de Aula'),
        ),
        migrations.AddField(
            model_name='periodotrabalho',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos_trabalho', to='core.funcionario'),
        ),
        migrations.AddField(
            model_name='professordisciplinaturma',
            name='disciplina_turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professores', to='core.disciplinaturma'),
        ),
        migrations.AddField(
            model_name='professordisciplinaturma',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes', to='core.funcionario'),
        ),
        migrations.AddField(
            model_name='turma',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='core.curso', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='turma',
            name='professores_representantes',
            field=models.ManyToManyField(related_name='turmas_representantes', to='core.funcionario', verbose_name='Professores Representantes'),
        ),
        migrations.AddField(
            model_name='disciplinaturma',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas_vinculadas', to='core.turma'),
        ),
        migrations.AlterUniqueTogether(
            name='controleregistrosvisualizacao',
            unique_together={('ano_letivo', 'bimestre', 'tipo')},
        ),
        migrations.AlterUniqueTogether(
            name='funcionario',
            unique_together={('usuario', 'matricula')},
        ),
        migrations.AlterUniqueTogether(
            name='horarioaula',
            unique_together={('ano_letivo', 'dia_semana', 'hora_inicio')},
        ),
        migrations.AlterUniqueTogether(
            name='gradehoraria',
            unique_together={('validade', 'horario_aula')},
        ),
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together={('numero', 'letra', 'ano_letivo', 'curso')},
        ),
        migrations.AlterUniqueTogether(
            name='disciplinaturma',
            unique_together={('disciplina', 'turma')},
        ),
    ]
