# Generated by Django 6.0 on 2025-12-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='matricula',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Número de matrícula do funcionário (máximo 32767)', null=True, unique=True, verbose_name='Nº Matrícula'),
        ),
    ]
