# Generated by Django 6.0 on 2025-12-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='professores_representantes',
            field=models.ManyToManyField(related_name='turmas_representantes', to='core.funcionario', verbose_name='Professores Representantes'),
        ),
    ]
