# Generated by Django 6.0 on 2026-01-02 12:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnoLetivoSelecionado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ano_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_selecionados', to='core.anoletivo', verbose_name='Ano Letivo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano_letivo_selecionado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ano Letivo Selecionado',
                'verbose_name_plural': 'Anos Letivos Selecionados',
            },
        ),
    ]
