# Generated by Django 6.0 on 2025-12-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinaturma',
            name='aulas_semanais',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='Aulas Semanais'),
        ),
    ]
