# Generated by Django 6.0 on 2026-01-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='visibilidade',
            field=models.CharField(choices=[('PRIVATE', 'Privado (Dono/Gestão)'), ('AUTHENTICATED', 'Qualquer Autenticado'), ('PUBLIC', 'Público')], default='PRIVATE', help_text='Define quem pode acessar este arquivo.', max_length=20, verbose_name='Visibilidade'),
        ),
    ]
