# Generated by Django 6.0 on 2025-12-29 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('pedagogical', '0002_alter_notabimestral_options_remove_aula_bimestre_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bimestre',
        ),
        migrations.DeleteModel(
            name='CalendarioEscolar',
        ),
    ]
