# Generated by Django 6.0 on 2025-12-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_turma_professores_representantes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professordisciplinaturma',
            options={'ordering': ['tipo', 'professor__usuario__first_name'], 'verbose_name': 'Atribuição de Professor', 'verbose_name_plural': 'Atribuições de Professores'},
        ),
        migrations.AddField(
            model_name='professordisciplinaturma',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fim'),
        ),
        migrations.AddField(
            model_name='professordisciplinaturma',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
        migrations.AddField(
            model_name='professordisciplinaturma',
            name='tipo',
            field=models.CharField(choices=[('TITULAR', 'Titular'), ('SUBSTITUTO', 'Substituto')], default='TITULAR', max_length=15, verbose_name='Tipo'),
        ),
    ]
