# Generated by Django 6.0 on 2025-12-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_bimestre_delete_calendarioescolar'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaLetivoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True, verbose_name='Data do Dia Letivo')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Motivo/Descrição')),
            ],
            options={
                'verbose_name': 'Dia Letivo Extra',
                'verbose_name_plural': 'Dias Letivos Extras',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='DiaNaoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True, verbose_name='Data da Ocorrência')),
                ('tipo', models.CharField(choices=[('FERIADO', 'Feriado'), ('PONTO_FACULTATIVO', 'Ponto facultativo'), ('RECESSO', 'Recesso escolar'), ('FERIAS', 'Férias escolares'), ('SUSPENSO', 'Dia letivo suspenso'), ('PLANEJAMENTO', 'Planejamento'), ('OUTROS', 'Outros')], max_length=30, verbose_name='Categoria do Dia')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Motivo/Descrição')),
            ],
            options={
                'verbose_name': 'Dia Não Letivo',
                'verbose_name_plural': 'Dias Não Letivos',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='AnoLetivo',
            fields=[
                ('ano', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Ano')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('data_inicio_1bim', models.DateField(blank=True, null=True, verbose_name='Data de Início do 1º Bimestre')),
                ('data_fim_1bim', models.DateField(blank=True, null=True, verbose_name='Data de Fim do 1º Bimestre')),
                ('data_inicio_2bim', models.DateField(blank=True, null=True, verbose_name='Data de Início do 2º Bimestre')),
                ('data_fim_2bim', models.DateField(blank=True, null=True, verbose_name='Data de Fim do 2º Bimestre')),
                ('data_inicio_3bim', models.DateField(blank=True, null=True, verbose_name='Data de Início do 3º Bimestre')),
                ('data_fim_3bim', models.DateField(blank=True, null=True, verbose_name='Data de Fim do 3º Bimestre')),
                ('data_inicio_4bim', models.DateField(blank=True, null=True, verbose_name='Início do 4º Bimestre')),
                ('data_fim_4bim', models.DateField(blank=True, null=True, verbose_name='Fim do 4º Bimestre')),
                ('dias_letivos_extras', models.ManyToManyField(blank=True, to='core.dialetivoextra', verbose_name='Dias Letivos Especiais')),
                ('dias_nao_letivos', models.ManyToManyField(blank=True, to='core.dianaoletivo', verbose_name='Feriados e Recessos')),
            ],
            options={
                'verbose_name': 'Ano Letivo',
                'verbose_name_plural': 'Anos Letivos',
                'ordering': ['-ano'],
            },
        ),
    ]
