# Generated by Django 6.0 on 2026-01-02 20:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_anoletivoselecionado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradehoraria',
            options={'ordering': ['horario_aula__dia_semana', 'horario_aula__hora_inicio'], 'verbose_name': 'Item de Grade Horária', 'verbose_name_plural': 'Itens de Grade Horária'},
        ),
        migrations.CreateModel(
            name='GradeHorariaValidade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_fim', models.DateField(verbose_name='Data de fim')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validades_grade', to='core.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Vigência de Grade Horária',
                'verbose_name_plural': 'Vigências de Grade Horária',
                'ordering': ['turma', '-data_inicio'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='gradehoraria',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gradehoraria',
            name='validade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_grade', to='core.gradehorariavalidade', verbose_name='Vigência'),
        ),
        migrations.AlterUniqueTogether(
            name='gradehoraria',
            unique_together={('validade', 'horario_aula')},
        ),
        migrations.RemoveField(
            model_name='gradehoraria',
            name='turma',
        ),
    ]
