# Generated by Django 6.0 on 2025-12-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_funcionario_matricula_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='matricula',
            field=models.PositiveIntegerField(help_text='Número de matrícula do funcionário', unique=True, verbose_name='Nº Matrícula'),
        ),
    ]
