# Generated by Django 6.0 on 2026-01-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_gradehoraria_options_gradehorariavalidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilidade',
            name='codigo',
            field=models.CharField(max_length=20, verbose_name='Código'),
        ),
    ]
