# Generated by Django 6.0 on 2025-12-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_funcionario_matricula_integer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplina',
            options={'ordering': ['area_conhecimento', 'nome'], 'verbose_name': 'Disciplina', 'verbose_name_plural': 'Disciplinas'},
        ),
        migrations.AddField(
            model_name='disciplina',
            name='area_conhecimento',
            field=models.CharField(choices=[('LINGUAGENS', 'Linguagens e suas Tecnologias'), ('MATEMATICA', 'Matemática e suas Tecnologias'), ('CIENCIAS_NATUREZA', 'Ciências da Natureza e suas Tecnologias'), ('CIENCIAS_HUMANAS', 'Ciências Humanas e Sociais Aplicadas'), ('TEC_INFORMATICA', 'Técnico em Informática'), ('TEC_QUIMICA', 'Técnico em Química'), ('TEC_ENFERMAGEM', 'Técnico em Enfermagem')], default='LINGUAGENS', max_length=20, verbose_name='Área de Conhecimento'),
        ),
    ]
