# Generated by Django 6.0 on 2025-12-30 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dialetivoextra_dianaoletivo_anoletivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Número da aula')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de início')),
                ('hora_fim', models.TimeField(verbose_name='Hora de fim')),
                ('ano_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_aula', to='core.anoletivo', verbose_name='Ano Letivo')),
            ],
            options={
                'verbose_name': 'Horário de Aula',
                'verbose_name_plural': 'Horários de Aula',
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('ano_letivo', 'dia_semana', 'hora_inicio')},
            },
        ),
        migrations.CreateModel(
            name='GradeHoraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades_horarias', to='core.disciplina', verbose_name='Disciplina')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades_horarias', to='core.turma', verbose_name='Turma')),
                ('horario_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades_horarias', to='core.horarioaula', verbose_name='Horário de Aula')),
            ],
            options={
                'verbose_name': 'Grade Horária',
                'verbose_name_plural': 'Grades Horárias',
                'ordering': ['horario_aula__dia_semana', 'horario_aula__hora_inicio'],
                'unique_together': {('turma', 'horario_aula')},
            },
        ),
    ]
