# Generated by Django 6.0 on 2025-12-24 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_tipo_datas_to_atribuicao'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='professordisciplinaturma',
            unique_together=set(),
        ),
    ]
