# Generated by Django 6.0 on 2026-01-03 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_habilidade_codigo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='habilidade',
            unique_together={('codigo', 'disciplina')},
        ),
    ]
