# Generated by Django 6.0 on 2025-12-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_unique_professor_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professordisciplinaturma',
            name='tipo',
            field=models.CharField(choices=[('TITULAR', 'Titular'), ('SUBSTITUTO', 'Substituto'), ('AUXILIAR', 'Auxiliar')], default='TITULAR', max_length=15, verbose_name='Tipo'),
        ),
    ]
