# Generated by Django 6.0 on 2026-01-04 13:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_habilidade_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleRegistrosVisualizacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bimestre', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Bimestre')),
                ('data_inicio', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('tipo', models.CharField(choices=[('AULA', 'Registro de Aula (falta e conteúdo)'), ('NOTA', 'Registro de Nota final do bimestre'), ('BOLETIM', 'Visualização do boletim')], default='AULA', max_length=10, verbose_name='Tipo')),
                ('liberado', models.BooleanField(default=False, verbose_name='Liberado')),
                ('ano_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controle_registros_visualizacao', to='core.anoletivo', verbose_name='Ano Letivo')),
            ],
            options={
                'verbose_name': 'Controle de Visualização de Registro',
                'verbose_name_plural': 'Controles de Visualização de Registros',
                'ordering': ['ano_letivo', 'bimestre', 'tipo'],
                'unique_together': {('ano_letivo', 'bimestre', 'tipo')},
            },
        ),
    ]
