# Generated by Django 6.0 on 2025-12-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_professordisciplinaturma_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='descontinuada',
            field=models.BooleanField(default=False, verbose_name='Descontinuada'),
        ),
        migrations.AlterUniqueTogether(
            name='disciplina',
            unique_together={('nome', 'sigla', 'descontinuada')},
        ),
    ]
