# Generated by Django 6.0 on 2026-01-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_controleregistrosvisualizacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controleregistrosvisualizacao',
            options={'ordering': ['ano_letivo', 'bimestre', 'tipo'], 'verbose_name': 'Controle de Registro/Visualização', 'verbose_name_plural': 'Controles de Registros/Visualizações'},
        ),
        migrations.AlterField(
            model_name='controleregistrosvisualizacao',
            name='bimestre',
            field=models.IntegerField(choices=[(1, '1º Bimestre'), (2, '2º Bimestre'), (3, '3º Bimestre'), (4, '4º Bimestre'), (5, 'Resultado Final')], default=1, verbose_name='Bimestre'),
        ),
    ]
