# Generated by Django 6.0 on 2025-12-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_descontinuada_to_disciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='area_conhecimento',
            field=models.CharField(blank=True, choices=[('LINGUAGENS', 'Linguagens e suas Tecnologias'), ('MATEMATICA', 'Matemática e suas Tecnologias'), ('CIENCIAS_NATUREZA', 'Ciências da Natureza e suas Tecnologias'), ('CIENCIAS_HUMANAS', 'Ciências Humanas e Sociais Aplicadas'), ('TEC_INFORMATICA', 'Técnico em Informática'), ('TEC_QUIMICA', 'Técnico em Química'), ('TEC_ENFERMAGEM', 'Técnico em Enfermagem')], max_length=20, null=True, verbose_name='Área de Conhecimento'),
        ),
    ]
