# Generated by Django 6.0 on 2026-01-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_controleregistrosvisualizacao_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controleregistrosvisualizacao',
            name='liberado',
        ),
        migrations.AlterField(
            model_name='controleregistrosvisualizacao',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
    ]
