# Generated by Django 6.0 on 2026-01-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_controleregistrosvisualizacao_liberado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controleregistrosvisualizacao',
            name='digitacao_futura',
            field=models.BooleanField(default=True, verbose_name='Permite digitação futura'),
        ),
    ]
