# Generated by Django 6.0 on 2026-01-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_controleregistrosvisualizacao_digitacao_futura'),
    ]

    operations = [
        migrations.AddField(
            model_name='anoletivo',
            name='controles',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Controles'),
        ),
    ]
