# Generated by Django 6.0 on 2026-01-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_anoletivo_controles'),
    ]

    operations = [
        migrations.AddField(
            model_name='anoletivo',
            name='datas_liberadas_aulas_faltas',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Cache de Datas Liberadas (Aulas/Faltas)'),
        ),
    ]
