# Generated by Django 6.0 on 2026-01-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_datas_liberadas_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='numero_cursos_atuando',
            field=models.PositiveIntegerField(default=0, verbose_name='Nº de Cursos Atuando'),
        ),
    ]
