# Generated by Django 6.0 on 2026-01-08 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_funcionario_numero_cursos_atuando'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='numero_cursos_atuando',
        ),
    ]
