# Generated by Django 6.0 on 2025-12-20 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('documento', models.FileField(blank=True, null=True, upload_to='avisos/', verbose_name='Documento Anexo')),
                ('data_aviso', models.DateTimeField(auto_now_add=True)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_criados', to='core.funcionario')),
                ('destinatarios', models.ManyToManyField(related_name='avisos_recebidos', to=settings.AUTH_USER_MODEL, verbose_name='Destinatários')),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
                'ordering': ['-data_aviso'],
            },
        ),
        migrations.CreateModel(
            name='ReuniaoHTPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reuniao', models.DateTimeField(verbose_name='Data da Reunião')),
                ('pauta', models.TextField(verbose_name='Pauta')),
                ('ata', models.TextField(blank=True, verbose_name='Ata')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('presentes', models.ManyToManyField(blank=True, related_name='htpcs_presentes', to='core.funcionario', verbose_name='Presentes')),
                ('quem_registrou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='htpcs_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reunião HTPC',
                'verbose_name_plural': 'Reuniões HTPC',
                'ordering': ['-data_reuniao'],
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('prazo', models.DateTimeField(verbose_name='Prazo')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluído')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='tarefas/', verbose_name='Documento Anexo')),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_criadas', to=settings.AUTH_USER_MODEL)),
                ('funcionarios', models.ManyToManyField(related_name='tarefas', to='core.funcionario', verbose_name='Funcionários Responsáveis')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['-prazo'],
            },
        ),
        migrations.CreateModel(
            name='AvisoVisualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visualizado', models.BooleanField(default=False)),
                ('data_visualizacao', models.DateTimeField(blank=True, null=True)),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to='management.aviso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_visualizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visualização de Aviso',
                'verbose_name_plural': 'Visualizações de Avisos',
                'unique_together': {('aviso', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='NotificacaoHTPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visualizado', models.BooleanField(default=False)),
                ('data_visualizacao', models.DateTimeField(blank=True, null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_htpc', to='core.funcionario')),
                ('reuniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='management.reuniaohtpc')),
            ],
            options={
                'verbose_name': 'Notificação de HTPC',
                'verbose_name_plural': 'Notificações de HTPC',
                'unique_together': {('reuniao', 'funcionario')},
            },
        ),
        migrations.CreateModel(
            name='NotificacaoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visualizado', models.BooleanField(default=False)),
                ('data_visualizacao', models.DateTimeField(blank=True, null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_tarefas', to='core.funcionario')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='management.tarefa')),
            ],
            options={
                'verbose_name': 'Notificação de Tarefa',
                'verbose_name_plural': 'Notificações de Tarefas',
                'unique_together': {('tarefa', 'funcionario')},
            },
        ),
    ]
