# Generated by Django 6.0 on 2025-12-21 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoVisualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visualizado', models.BooleanField(default=False)),
                ('data_visualizacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Visualização de Aviso',
                'verbose_name_plural': 'Visualizações de Avisos',
            },
        ),
        migrations.CreateModel(
            name='NotificacaoHTPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visualizado', models.BooleanField(default=False)),
                ('data_visualizacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notificação de HTPC',
                'verbose_name_plural': 'Notificações de HTPC',
            },
        ),
        migrations.CreateModel(
            name='NotificacaoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visualizado', models.BooleanField(default=False)),
                ('data_visualizacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notificação de Tarefa',
                'verbose_name_plural': 'Notificações de Tarefas',
            },
        ),
        migrations.CreateModel(
            name='ReuniaoHTPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reuniao', models.DateTimeField(verbose_name='Data da Reunião')),
                ('pauta', models.TextField(verbose_name='Pauta')),
                ('ata', models.TextField(blank=True, verbose_name='Ata')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reunião HTPC',
                'verbose_name_plural': 'Reuniões HTPC',
                'ordering': ['-data_reuniao'],
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('prazo', models.DateTimeField(verbose_name='Prazo')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluído')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='tarefas/', verbose_name='Documento Anexo')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['-prazo'],
            },
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('documento', models.FileField(blank=True, null=True, upload_to='avisos/', verbose_name='Documento Anexo')),
                ('data_aviso', models.DateTimeField(auto_now_add=True)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_criados', to='core.funcionario')),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
                'ordering': ['-data_aviso'],
            },
        ),
    ]
