# Generated by Django 6.0 on 2025-12-22 10:33

import apps.management.models
import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=apps.management.models.get_anexo_path, verbose_name='Arquivo')),
                ('descricao', models.CharField(blank=True, max_length=100, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Anexo do Aviso',
                'verbose_name_plural': 'Anexos do Aviso',
            },
        ),
        migrations.CreateModel(
            name='AvisoVisualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visualizado', models.BooleanField(default=False)),
                ('data_visualizacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Visualização de Aviso',
                'verbose_name_plural': 'Visualizações de Avisos',
            },
        ),
        migrations.CreateModel(
            name='NotificacaoHTPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visualizado', models.BooleanField(default=False)),
                ('data_visualizacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notificação de HTPC',
                'verbose_name_plural': 'Notificações de HTPC',
            },
        ),
        migrations.CreateModel(
            name='NotificacaoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visualizado', models.BooleanField(default=False)),
                ('data_visualizacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notificação de Tarefa',
                'verbose_name_plural': 'Notificações de Tarefas',
            },
        ),
        migrations.CreateModel(
            name='ReuniaoHTPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reuniao', models.DateTimeField(verbose_name='Data da Reunião')),
                ('pauta', ckeditor.fields.RichTextField(verbose_name='Pauta')),
                ('ata', ckeditor.fields.RichTextField(blank=True, verbose_name='Ata')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reunião HTPC',
                'verbose_name_plural': 'Reuniões HTPC',
                'ordering': ['-data_reuniao'],
            },
        ),
        migrations.CreateModel(
            name='ReuniaoHTPCAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=apps.management.models.get_anexo_path, verbose_name='Arquivo')),
                ('descricao', models.CharField(blank=True, max_length=100, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Anexo de HTPC',
                'verbose_name_plural': 'Anexos de HTPC',
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', ckeditor.fields.RichTextField(blank=True, verbose_name='Descrição')),
                ('prazo', models.DateTimeField(verbose_name='Prazo')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluído')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['-prazo'],
            },
        ),
        migrations.CreateModel(
            name='TarefaAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=apps.management.models.get_anexo_path, verbose_name='Arquivo')),
                ('descricao', models.CharField(blank=True, max_length=100, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Anexo da Tarefa',
                'verbose_name_plural': 'Anexos da Tarefa',
            },
        ),
        migrations.CreateModel(
            name='TarefaResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', ckeditor.fields.RichTextField(blank=True, verbose_name='Mensagem/Resposta')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Resposta da Tarefa',
                'verbose_name_plural': 'Respostas da Tarefa',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='TarefaRespostaAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=apps.management.models.get_anexo_path, verbose_name='Arquivo')),
                ('descricao', models.CharField(blank=True, max_length=100, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Anexo da Resposta',
                'verbose_name_plural': 'Anexos da Resposta',
            },
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('texto', ckeditor.fields.RichTextField(verbose_name='Texto')),
                ('data_aviso', models.DateTimeField(auto_now_add=True)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_criados', to='core.funcionario')),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
                'ordering': ['-data_aviso'],
            },
        ),
    ]
