# Generated by Django 6.0 on 2026-01-13 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='destinatarios',
            field=models.ManyToManyField(related_name='avisos_recebidos', to=settings.AUTH_USER_MODEL, verbose_name='Destinatários'),
        ),
        migrations.AddField(
            model_name='avisoanexo',
            name='aviso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='management.aviso'),
        ),
        migrations.AddField(
            model_name='avisovisualizacao',
            name='aviso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to='management.aviso'),
        ),
        migrations.AddField(
            model_name='avisovisualizacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_visualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificacaohtpc',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_htpc', to='core.funcionario'),
        ),
        migrations.AddField(
            model_name='notificacaotarefa',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_tarefas', to='core.funcionario'),
        ),
        migrations.AddField(
            model_name='reuniaohtpc',
            name='presentes',
            field=models.ManyToManyField(blank=True, related_name='htpcs_presentes', to='core.funcionario', verbose_name='Presentes'),
        ),
        migrations.AddField(
            model_name='reuniaohtpc',
            name='quem_registrou',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='htpcs_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificacaohtpc',
            name='reuniao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='management.reuniaohtpc'),
        ),
        migrations.AddField(
            model_name='reuniaohtpcanexo',
            name='reuniao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='management.reuniaohtpc'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='criador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='funcionarios',
            field=models.ManyToManyField(related_name='tarefas', to='core.funcionario', verbose_name='Funcionários Responsáveis'),
        ),
        migrations.AddField(
            model_name='notificacaotarefa',
            name='tarefa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='management.tarefa'),
        ),
        migrations.AddField(
            model_name='tarefaanexo',
            name='tarefa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='management.tarefa'),
        ),
        migrations.AddField(
            model_name='tarefaresposta',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_tarefa', to='core.funcionario'),
        ),
        migrations.AddField(
            model_name='tarefaresposta',
            name='tarefa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='management.tarefa'),
        ),
        migrations.AddField(
            model_name='tarefarespostaanexo',
            name='resposta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='management.tarefaresposta'),
        ),
        migrations.AlterUniqueTogether(
            name='avisovisualizacao',
            unique_together={('aviso', 'usuario')},
        ),
        migrations.AlterUniqueTogether(
            name='notificacaohtpc',
            unique_together={('reuniao', 'funcionario')},
        ),
        migrations.AlterUniqueTogether(
            name='notificacaotarefa',
            unique_together={('tarefa', 'funcionario')},
        ),
    ]
