# Generated by Django 6.0 on 2025-12-21 14:03

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('conteudo', ckeditor.fields.RichTextField(verbose_name='Conteúdo Ministrado')),
                ('numero_aulas', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Número de Aulas (Geminadas)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('bimestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.bimestre', verbose_name='Bimestre')),
                ('professor_disciplina_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='core.professordisciplinaturma')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ['-data'],
                'unique_together': {('professor_disciplina_turma', 'data')},
            },
        ),
        migrations.CreateModel(
            name='DescritorOcorrenciaPedagogica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=100, verbose_name='Descrição do Tipo')),
                ('ativo', models.BooleanField(default=True)),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_ocorrencia_criados', to='core.funcionario')),
            ],
            options={
                'verbose_name': 'Tipo de Ocorrência',
                'verbose_name_plural': 'Tipos de Ocorrências',
                'ordering': ['texto'],
            },
        ),
        migrations.CreateModel(
            name='NotificacaoRecuperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visualizado', models.BooleanField(default=False)),
                ('data_visualizacao', models.DateTimeField(blank=True, null=True)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_recuperacao', to='academic.estudante')),
                ('professor_disciplina_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_recuperacao', to='core.professordisciplinaturma')),
            ],
            options={
                'verbose_name': 'Notificação de Recuperação',
                'verbose_name_plural': 'Notificações de Recuperação',
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaPedagogica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_criadas', to='core.funcionario')),
                ('bimestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.bimestre', verbose_name='Bimestre')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_pedagogicas', to='academic.estudante')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to='pedagogical.descritorocorrenciapedagogica')),
            ],
            options={
                'verbose_name': 'Ocorrência Pedagógica',
                'verbose_name_plural': 'Ocorrências Pedagógicas',
                'ordering': ['-data', 'estudante'],
            },
        ),
        migrations.CreateModel(
            name='PlanoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data Início')),
                ('data_fim', models.DateField(verbose_name='Data Fim')),
                ('conteudo', ckeditor.fields.RichTextField(verbose_name='Conteúdo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('bimestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.bimestre', verbose_name='Bimestre')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planos_aula', to='core.disciplina')),
                ('habilidades', models.ManyToManyField(blank=True, related_name='planos_aula', to='core.habilidade')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_aula', to='core.funcionario')),
                ('turmas', models.ManyToManyField(related_name='planos_aula', to='core.turma')),
            ],
            options={
                'verbose_name': 'Plano de Aula',
                'verbose_name_plural': 'Planos de Aula',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('10.00'))], verbose_name='Valor da Avaliação')),
                ('tipo', models.CharField(choices=[('AVALIACAO_REGULAR', 'Avaliação Regular'), ('AVALIACAO_RECUPERACAO', 'Avaliação de Recuperação'), ('AVALIACAO_EXTRA', 'Avaliação Extra')], default='AVALIACAO_REGULAR', max_length=30, verbose_name='Tipo de Avaliação')),
                ('tipo_calculo_instrumentos', models.CharField(choices=[('MEDIA_PONDERADA', 'Média Ponderada'), ('SOMA', 'Soma')], default='SOMA', max_length=20, verbose_name='Tipo de Cálculo de Instrumentos')),
                ('bimestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.bimestre', verbose_name='Bimestre')),
                ('matricula_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='academic.matriculaturma')),
                ('professor_disciplina_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='core.professordisciplinaturma')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'unique_together': {('matricula_turma', 'professor_disciplina_turma')},
            },
        ),
        migrations.CreateModel(
            name='Faltas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aula_numero', models.PositiveSmallIntegerField(help_text='Número da aula no dia (1, 2, 3 ou 4)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Aula Nº')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltas', to='pedagogical.aula')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltas', to='academic.estudante')),
            ],
            options={
                'verbose_name': 'Falta',
                'verbose_name_plural': 'Faltas',
                'unique_together': {('aula', 'estudante', 'aula_numero')},
            },
        ),
        migrations.CreateModel(
            name='NotaBimestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('10.00'))], verbose_name='Nota')),
                ('bimestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.bimestre', verbose_name='Bimestre')),
                ('matricula_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='academic.matriculaturma')),
                ('professor_disciplina_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='core.professordisciplinaturma')),
            ],
            options={
                'verbose_name': 'Nota Bimestral',
                'verbose_name_plural': 'Notas Bimestrais',
                'ordering': ['matricula_turma', 'bimestre'],
                'unique_together': {('matricula_turma', 'professor_disciplina_turma', 'bimestre')},
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaResponsavelCiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciente', models.BooleanField(default=False)),
                ('data_ciencia', models.DateTimeField(blank=True, null=True)),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciencias', to='pedagogical.ocorrenciapedagogica')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciencias_ocorrencias', to='academic.responsavel')),
            ],
            options={
                'verbose_name': 'Ciência de Ocorrência',
                'verbose_name_plural': 'Ciências de Ocorrências',
                'unique_together': {('responsavel', 'ocorrencia')},
            },
        ),
    ]
