# Generated by Django 6.0 on 2026-01-13 18:02

import ckeditor.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField(verbose_name='Data')),
                ('conteudo', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Conteúdo Ministrado')),
                ('numero_aulas', models.PositiveSmallIntegerField(default=2, verbose_name='Número de Aulas (Geminadas)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('bimestre', models.PositiveSmallIntegerField(choices=[(0, 'Anual'), (1, '1º Bimestre'), (2, '2º Bimestre'), (3, '3º Bimestre'), (4, '4º Bimestre')], default=0, verbose_name='Bimestre')),
                ('professor_disciplina_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='core.professordisciplinaturma')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ['-data'],
                'unique_together': {('professor_disciplina_turma', 'data')},
            },
        ),
        migrations.CreateModel(
            name='DescritorOcorrenciaPedagogica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=100, verbose_name='Descrição do Tipo')),
                ('ativo', models.BooleanField(default=True)),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_ocorrencia_criados', to='core.funcionario')),
            ],
            options={
                'verbose_name': 'Tipo de Ocorrência',
                'verbose_name_plural': 'Tipos de Ocorrências',
                'ordering': ['texto'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaPedagogica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('bimestre', models.PositiveSmallIntegerField(choices=[(0, 'Anual'), (1, '1º Bimestre'), (2, '2º Bimestre'), (3, '3º Bimestre'), (4, '4º Bimestre')], default=0, verbose_name='Bimestre')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_criadas', to='core.funcionario')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_pedagogicas', to='academic.estudante')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to='pedagogical.descritorocorrenciapedagogica')),
            ],
            options={
                'verbose_name': 'Ocorrência Pedagógica',
                'verbose_name_plural': 'Ocorrências Pedagógicas',
                'ordering': ['-data', 'estudante'],
            },
        ),
        migrations.CreateModel(
            name='PlanoAula',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('data_inicio', models.DateField(verbose_name='Data Início')),
                ('data_fim', models.DateField(verbose_name='Data Fim')),
                ('conteudo', ckeditor.fields.RichTextField(blank=True, verbose_name='Conteúdo')),
                ('bimestre', models.PositiveSmallIntegerField(choices=[(0, 'Anual'), (1, '1º Bimestre'), (2, '2º Bimestre'), (3, '3º Bimestre'), (4, '4º Bimestre')], default=0, verbose_name='Bimestre')),
                ('ano_letivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planos_aula', to='core.anoletivo', verbose_name='Ano Letivo')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planos_aula', to='core.disciplina')),
                ('habilidades', models.ManyToManyField(blank=True, related_name='planos_aula', to='core.habilidade')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_aula', to='core.funcionario')),
                ('turmas', models.ManyToManyField(blank=True, related_name='planos_aula', to='core.turma')),
            ],
            options={
                'verbose_name': 'Plano de Aula',
                'verbose_name_plural': 'Planos de Aula',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Faltas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aulas_faltas', models.JSONField(blank=True, default=list, null=True, verbose_name='Índice das Aulas com Falta')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltas', to='pedagogical.aula')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltas', to='academic.estudante')),
            ],
            options={
                'verbose_name': 'Falta',
                'verbose_name_plural': 'Faltas',
                'unique_together': {('aula', 'estudante')},
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaResponsavelCiente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ciente', models.BooleanField(default=False)),
                ('data_ciencia', models.DateTimeField(blank=True, null=True)),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciencias', to='pedagogical.ocorrenciapedagogica')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciencias_ocorrencias', to='academic.responsavel')),
            ],
            options={
                'verbose_name': 'Ciência de Ocorrência',
                'verbose_name_plural': 'Ciências de Ocorrências',
                'unique_together': {('responsavel', 'ocorrencia')},
            },
        ),
    ]
