# Generated by Django 6.0 on 2025-12-29 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
        ('core', '0002_initial'),
        ('pedagogical', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notabimestral',
            options={'ordering': ['matricula_turma'], 'verbose_name': 'Nota Bimestral', 'verbose_name_plural': 'Notas Bimestrais'},
        ),
        migrations.RemoveField(
            model_name='aula',
            name='bimestre',
        ),
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together={('professor_disciplina_turma', 'tipo')},
        ),
        migrations.AlterUniqueTogether(
            name='notabimestral',
            unique_together={('matricula_turma', 'professor_disciplina_turma')},
        ),
        migrations.RemoveField(
            model_name='ocorrenciapedagogica',
            name='bimestre',
        ),
        migrations.RemoveField(
            model_name='planoaula',
            name='bimestre',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='bimestre',
        ),
        migrations.RemoveField(
            model_name='notabimestral',
            name='bimestre',
        ),
    ]
