# Generated by Django 6.0 on 2026-01-17 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('core', '0002_initial'),
        ('pedagogical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='habilidades',
            field=models.ManyToManyField(blank=True, related_name='atividades', to='core.habilidade'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='turmas_professores',
            field=models.ManyToManyField(related_name='atividades', to='core.professordisciplinaturma', verbose_name='Professores/Disciplinas/Turmas'),
        ),
        migrations.AddField(
            model_name='aula',
            name='professor_disciplina_turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='core.professordisciplinaturma'),
        ),
        migrations.AddField(
            model_name='faltas',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltas', to='pedagogical.aula'),
        ),
        migrations.AddField(
            model_name='faltas',
            name='estudante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltas', to='academic.estudante'),
        ),
        migrations.AddField(
            model_name='ocorrenciapedagogica',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_criadas', to='core.funcionario'),
        ),
        migrations.AddField(
            model_name='ocorrenciapedagogica',
            name='estudante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_pedagogicas', to='academic.estudante'),
        ),
        migrations.AddField(
            model_name='ocorrenciapedagogica',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to='pedagogical.descritorocorrenciapedagogica'),
        ),
        migrations.AddField(
            model_name='ocorrenciaresponsavelciente',
            name='ocorrencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciencias', to='pedagogical.ocorrenciapedagogica'),
        ),
        migrations.AddField(
            model_name='ocorrenciaresponsavelciente',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciencias_ocorrencias', to='academic.responsavel'),
        ),
        migrations.AddField(
            model_name='planoaula',
            name='ano_letivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planos_aula', to='core.anoletivo', verbose_name='Ano Letivo'),
        ),
        migrations.AddField(
            model_name='planoaula',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planos_aula', to='core.disciplina'),
        ),
        migrations.AddField(
            model_name='planoaula',
            name='habilidades',
            field=models.ManyToManyField(blank=True, related_name='planos_aula', to='core.habilidade'),
        ),
        migrations.AddField(
            model_name='planoaula',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_aula', to='core.funcionario'),
        ),
        migrations.AddField(
            model_name='planoaula',
            name='turmas',
            field=models.ManyToManyField(blank=True, related_name='planos_aula', to='core.turma'),
        ),
        migrations.AlterUniqueTogether(
            name='aula',
            unique_together={('professor_disciplina_turma', 'data')},
        ),
        migrations.AlterUniqueTogether(
            name='faltas',
            unique_together={('aula', 'estudante')},
        ),
        migrations.AlterUniqueTogether(
            name='ocorrenciaresponsavelciente',
            unique_together={('responsavel', 'ocorrencia')},
        ),
    ]
