# Generated by Django 6.0 on 2026-01-05 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_controleregistrosvisualizacao_digitacao_futura'),
        ('pedagogical', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planoaula',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='planoaula',
            name='criado_em',
        ),
        migrations.AddField(
            model_name='planoaula',
            name='ano_letivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planos_aula', to='core.anoletivo', verbose_name='Ano Letivo'),
        ),
        migrations.AddField(
            model_name='planoaula',
            name='bimestre',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Anual'), (1, '1º Bimestre'), (2, '2º Bimestre'), (3, '3º Bimestre'), (4, '4º Bimestre')], default=0, verbose_name='Bimestre'),
        ),
        migrations.AlterField(
            model_name='planoaula',
            name='turmas',
            field=models.ManyToManyField(blank=True, related_name='planos_aula', to='core.turma'),
        ),
    ]
