# Generated by Django 6.0 on 2026-01-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogical', '0002_remove_planoaula_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoaula',
            name='titulo',
            field=models.CharField(default='Plano de Aula', max_length=100, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
