# Generated by Django 6.0 on 2026-01-06 09:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogical', '0003_planoaula_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planoaula',
            name='conteudo',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Conteúdo'),
        ),
    ]
