# Generated by Django 6.0 on 2026-01-06 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogical', '0004_alter_planoaula_conteudo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planoaula',
            name='ano_letivo',
        ),
    ]
