# Generated by Django 6.0 on 2026-01-06 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_controleregistrosvisualizacao_digitacao_futura'),
        ('pedagogical', '0005_remove_planoaula_ano_letivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoaula',
            name='ano_letivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planos_aula', to='core.anoletivo', verbose_name='Ano Letivo'),
        ),
    ]
