# Generated by Django 6.0 on 2026-01-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_alter_matriculaturma_status'),
        ('pedagogical', '0006_planoaula_ano_letivo'),
    ]

    operations = [
        # First, remove the old unique_together constraint (that used aula_numero)
        migrations.AlterUniqueTogether(
            name='faltas',
            unique_together=set(),
        ),
        # Remove the old field
        migrations.RemoveField(
            model_name='faltas',
            name='aula_numero',
        ),
        # Add new fields
        migrations.AddField(
            model_name='aula',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='faltas',
            name='qtd_faltas',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Quantidade de Faltas'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='numero_aulas',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Número de Aulas (Geminadas)'),
        ),
        # Finally, set the new unique_together with the new field
        migrations.AlterUniqueTogether(
            name='faltas',
            unique_together={('aula', 'estudante')},
        ),
    ]
