# Generated by Django 6.0 on 2026-01-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogical', '0007_alter_faltas_unique_together_aula_atualizado_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faltas',
            name='qtd_faltas',
        ),
        migrations.AddField(
            model_name='faltas',
            name='aulas_faltas',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Índice das Aulas com Falta'),
        ),
    ]
