# Generated by Django 6.0 on 2026-01-07 16:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogical', '0008_remove_faltas_qtd_faltas_faltas_aulas_faltas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='conteudo',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Conteúdo Ministrado'),
        ),
    ]
