# Generated by Django 6.0 on 2026-01-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogical', '0009_alter_aula_conteudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='bimestre',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Anual'), (1, '1º Bimestre'), (2, '2º Bimestre'), (3, '3º Bimestre'), (4, '4º Bimestre')], default=0, verbose_name='Bimestre'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='bimestre',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Anual'), (1, '1º Bimestre'), (2, '2º Bimestre'), (3, '3º Bimestre'), (4, '4º Bimestre')], default=0, verbose_name='Bimestre'),
        ),
        migrations.AddField(
            model_name='controlevisto',
            name='bimestre',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Anual'), (1, '1º Bimestre'), (2, '2º Bimestre'), (3, '3º Bimestre'), (4, '4º Bimestre')], default=0, verbose_name='Bimestre'),
        ),
        migrations.AddField(
            model_name='faltas',
            name='bimestre',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Anual'), (1, '1º Bimestre'), (2, '2º Bimestre'), (3, '3º Bimestre'), (4, '4º Bimestre')], default=0, verbose_name='Bimestre'),
        ),
        migrations.AddField(
            model_name='instrumentoavaliativo',
            name='bimestre',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Anual'), (1, '1º Bimestre'), (2, '2º Bimestre'), (3, '3º Bimestre'), (4, '4º Bimestre')], default=0, verbose_name='Bimestre'),
        ),
        migrations.AddField(
            model_name='notabimestral',
            name='bimestre',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Anual'), (1, '1º Bimestre'), (2, '2º Bimestre'), (3, '3º Bimestre'), (4, '4º Bimestre')], default=0, verbose_name='Bimestre'),
        ),
        migrations.AddField(
            model_name='ocorrenciapedagogica',
            name='bimestre',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Anual'), (1, '1º Bimestre'), (2, '2º Bimestre'), (3, '3º Bimestre'), (4, '4º Bimestre')], default=0, verbose_name='Bimestre'),
        ),
    ]
