# Generated by Django 6.0 on 2026-01-08 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogical', '0010_add_bimestre_field_to_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faltas',
            name='bimestre',
        ),
    ]
