# Generated by Django 6.0 on 2025-12-31 16:34

import apps.core.validators
import ckeditor.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosPermanenteEstudante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[apps.core.validators.validate_cpf], verbose_name='CPF')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('telefone', models.CharField(blank=True, max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('endereco_completo', models.TextField(blank=True, verbose_name='Endereço Completo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dados Permanentes do Estudante',
                'verbose_name_plural': 'Dados Permanentes dos Estudantes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DadosPermanenteResponsavel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[apps.core.validators.validate_cpf], verbose_name='CPF')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('parentesco', models.CharField(blank=True, choices=[('PAI', 'Pai'), ('MAE', 'Mãe'), ('AVO_M', 'Avô(a) Materno'), ('AVO_P', 'Avô(a) Paterno'), ('TIO', 'Tio(a)'), ('IRMAO', 'Irmão(ã)'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Parentesco')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to='permanent.dadospermanenteestudante')),
            ],
            options={
                'verbose_name': 'Dados Permanentes do Responsável',
                'verbose_name_plural': 'Dados Permanentes dos Responsáveis',
            },
        ),
        migrations.CreateModel(
            name='HistoricoEscolar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_matricula', models.CharField(max_length=20, verbose_name='Número da Matrícula')),
                ('nome_curso', models.CharField(max_length=100, verbose_name='Nome do Curso')),
                ('data_entrada_cemep', models.DateField(verbose_name='Data de Entrada no CEMEP')),
                ('data_saida_cemep', models.DateField(blank=True, null=True, verbose_name='Data de Saída do CEMEP')),
                ('concluido', models.BooleanField(default=False, verbose_name='Curso Concluído')),
                ('observacoes_gerais', ckeditor.fields.RichTextField(blank=True, verbose_name='Observações Gerais')),
                ('estudante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='permanent.dadospermanenteestudante')),
            ],
            options={
                'verbose_name': 'Histórico Escolar',
                'verbose_name_plural': 'Históricos Escolares',
            },
        ),
        migrations.CreateModel(
            name='HistoricoEscolarAnoLetivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ano_letivo', models.PositiveSmallIntegerField(verbose_name='Ano Letivo')),
                ('nomenclatura_turma', models.CharField(max_length=50, verbose_name='Nomenclatura da Turma')),
                ('numero_turma', models.PositiveSmallIntegerField(verbose_name='Número da Turma')),
                ('letra_turma', models.CharField(default='A', max_length=1, verbose_name='Letra da Turma')),
                ('status_final', models.CharField(choices=[('RETIDO', 'Retido'), ('PROMOVIDO', 'Promovido')], max_length=20, verbose_name='Status Final')),
                ('descricao_status', models.CharField(max_length=100, verbose_name='Descrição do Status')),
                ('observacoes', ckeditor.fields.RichTextField(blank=True, verbose_name='Observações')),
                ('historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anos_letivos', to='permanent.historicoescolar')),
            ],
            options={
                'verbose_name': 'Histórico por Ano Letivo',
                'verbose_name_plural': 'Históricos por Ano Letivo',
                'ordering': ['ano_letivo'],
                'unique_together': {('historico', 'ano_letivo')},
            },
        ),
        migrations.CreateModel(
            name='HistoricoEscolarNotas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_disciplina', models.CharField(max_length=100, verbose_name='Nome da Disciplina')),
                ('aulas_semanais', models.PositiveSmallIntegerField(verbose_name='Aulas Semanais')),
                ('nota_final', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Nota Final')),
                ('frequencia_total', models.PositiveSmallIntegerField(help_text='Porcentagem de frequência', verbose_name='Frequência Total (%)')),
                ('ano_letivo_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='permanent.historicoescolaranoletivo')),
            ],
            options={
                'verbose_name': 'Nota Final do Histórico',
                'verbose_name_plural': 'Notas Finais do Histórico',
                'ordering': ['nome_disciplina'],
            },
        ),
        migrations.CreateModel(
            name='RegistroProntuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ocorrencia_disciplinar', models.BooleanField(default=True, verbose_name='Ocorrência Disciplinar')),
                ('cpf', models.CharField(db_index=True, max_length=14, validators=[apps.core.validators.validate_cpf], verbose_name='CPF do Estudante')),
                ('nome_estudante', models.CharField(max_length=255, verbose_name='Nome do Estudante')),
                ('autor_nome', models.CharField(max_length=255, verbose_name='Nome do Autor')),
                ('data_ocorrido', models.DateTimeField(verbose_name='Data da Ocorrência')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data do Registro')),
                ('descricao', ckeditor.fields.RichTextField(verbose_name='Descrição')),
                ('ano_letivo', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ano Letivo')),
                ('bimestre', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Bimestre')),
                ('pai_ocorrencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhas', to='permanent.registroprontuario', verbose_name='Registro Pai')),
            ],
            options={
                'verbose_name': 'Registro de Prontuário',
                'verbose_name_plural': 'Registros de Prontuário',
                'ordering': ['-data_ocorrido'],
            },
        ),
        migrations.CreateModel(
            name='RegistroProntuarioAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='registro_prontuario/', verbose_name='Arquivo')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição do Anexo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('registro_prontuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='permanent.registroprontuario')),
            ],
            options={
                'verbose_name': 'Anexo de Registro Prontuário',
                'verbose_name_plural': 'Anexos de Registro Prontuário',
            },
        ),
    ]
